repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.10
  hooks:
    - id: shellcheck
    - id: terraform-fmt
      args: ["-recursive"]
    - id: terragrunt-hclfmt
    - id: tflint
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.43.0
  hooks:
    - id: terraform_tfsec
    - id: checkov
- repo: local
  hooks:
    - id: generate-terraform-docs
      name: Generate Terraform README files
      always_run: true
      entry: find . -name ".terraform-docs.yml" -not -path "*/template/*" -exec sh -c 'dirname $0 | xargs -n 1 -I % sh -c "{ terraform-docs % > %/README.md; }"' {} \;
      language: system
      pass_filenames: false
